export const INDEX_OPTIONS = [
  { label: "Nifty", value: "NIFTY" },
  { label: "Nifty Bank", value: "BANKNIFTY" },
  { label: "Nifty Fin Service", value: "FINNIFTY" },
  { label: "Sensex", value: "SENSEX" },
  { label: "India VIX", value: "INDIAVIX" },
  { label: "Nifty Midcap 100", value: "MIDCPNIFTY" },
  { label: "Nifty 100", value: "NIFTY100" },
  { label: "Nifty PSU Bank", value: "NIFTYPSUBANK" },
  { label: "Nifty Pharma", value: "NIFTYPHARMA" },
  { label: "Nifty IT", value: "NIFTYIT" },
  { label: "Nifty PSE", value: "NIFTYPSE" },
  { label: "Nifty FMCG", value: "NIFTYFMCG" },
  { label: "Nifty 500", value: "NIFTY500" },
  { label: "Nifty Auto", value: "NIFTYAUTO" },
  { label: "Nifty CPSE", value: "NIFTYCPSE" },
  { label: "Nifty 200", value: "NIFTY200" },
  { label: "Nifty Next 50", value: "NIFTYNEXT50" },
  { label: "Nifty Mid Select", value: "NIFTYMIDSELECT" },
];
